apiVersion: apps/v1
kind: Deployment
metadata:
  name: pensionauthorizationapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Auth.API
  template:
    metadata:
      labels:
        app: Auth.API
    spec:
      containers:
      - name: pensionauthorizationrepos
        image:  authregistry1.azurecr.io/conatinerregistry:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret  



---
apiVersion: v1
kind: Service
metadata:
  name: pensionauthorizationapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Auth.API
